### PR TITLE
Add Portuguese locale (PT-BR)

### PR DESCRIPTION
**Pull request by luissilva1044894**

### CODE REVIEW

**Comment by V10lator** [comment]
@luissilva1044894 Are you on Discord, too, and if so: What's your name there?

**Comment by luissilva1044894** [comment]
Which Discord Server (I guess)? I'm using Discord only for a few Homebrew servers rn

**Comment by V10lator** [comment]
https://discord.gg/B8ZBd6mrnV - Would be great if you could join so we can add you to the team. That way you will be notified when translation updates are needed.

**Comment by luissilva1044894** [comment]
Didn't knew it, joined! (Nonsocial)

**Pull request merged**
